services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - media_data:/app/media # <--- Сохраняем медиа-файлы в отдельный том

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      - WATCHPACK_POLLING=true 
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  media_data: # <--- Объявляем том для медиа

